import type {
  ActivitySession,
  Announcement,
  Assignment,
  Challan,
  Course,
  CourseProgress,
  CourseSelection,
  EvaluationQuestion,
  Gdb,
  GradeBookEntry,
  GradingSchemeRow,
  LectureSlot,
  Lesson,
  LoginHistory,
  MailMessage,
  MidtermRow,
  Note,
  Quiz,
  Student,
  StudentProfile,
  StudentServiceLink,
  StudySchemeCourse,
  TodoItem,
} from "@vu-lms/shared";
import { CURRENT_SEMESTER, DEMO_PASSWORD, DEMO_STUDENT_ID } from "@vu-lms/shared";

export const student: Student = {
  id: "stu-1",
  studentId: DEMO_STUDENT_ID,
  name: "ARSLAN JAFER",
  program: "BS (Information Technology)",
  cgpa: 2.18,
  effectiveCgpa: 2.38,
  creditsEarned: 65,
  creditsExempted: 0,
  currentSemesterNo: 7,
  avatarUrl: null,
  validUpto: "May 2027",
  email: `${DEMO_STUDENT_ID}@vu.edu.pk`,
  formNo: "BW346377",
  vuRegistrationNo: "023-VU-001227",
  admissionDate: "Mar 14, 2023",
  virtualCampusCode: "PBAD01",
  fieldOfStudy: "Information Technology",
};

export const studentProfile: StudentProfile = {
  summary: {
    name: student.name,
    studentId: student.studentId,
    email: student.email!,
    fieldOfStudy: student.fieldOfStudy!,
    avatarUrl: null,
  },
  studentProfile: {
    "Form No": student.formNo!,
    "VU Registration No": student.vuRegistrationNo!,
    "Study Program": student.fieldOfStudy!,
    "Admission Date": student.admissionDate!,
    "Virtual Campus Code": student.virtualCampusCode!,
    "Current Semester No": String(student.currentSemesterNo),
  },
  personalInformation: {
    "Father Name": "JAFER HUSSAIN",
    Gender: "Male",
    "Date of Birth": "15-Aug-2003",
    CNIC: "35202-XXXXXXX-1",
    City: "Lahore",
    Mobile: "0300-XXXXXXX",
  },
  academicHistory: [
    {
      degree: "Intermediate (ICS)",
      institute: "Punjab Board",
      year: "2022",
      marks: "78%",
    },
    {
      degree: "Matriculation",
      institute: "Punjab Board",
      year: "2020",
      marks: "82%",
    },
  ],
  correctionNote:
    "Note: For any correction or change is required in your profile information, please write to studentprofile@vu.edu.pk",
};

export const loginHistory: LoginHistory[] = [
  {
    id: "lh1",
    at: "2026-07-22T08:15:00.000Z",
    ip: "39.50.12.88",
    device: "Chrome / Windows",
    location: "Lahore, PK",
  },
  {
    id: "lh2",
    at: "2026-07-21T19:40:00.000Z",
    ip: "39.50.12.88",
    device: "VU LMS Mobile",
    location: "Lahore, PK",
  },
  {
    id: "lh3",
    at: "2026-07-18T11:05:00.000Z",
    ip: "182.180.44.10",
    device: "Firefox / Android",
    location: "Islamabad, PK",
  },
];

export const credentials = {
  studentId: DEMO_STUDENT_ID,
  password: DEMO_PASSWORD as string,
};

export const courses: Course[] = [
  {
    id: "c-cs201p",
    code: "CS201P",
    title: "Introduction to Programming (Practical)",
    department: "Computer Science/Information Technology",
    creditHours: 1,
    instructorName: "Dr. Naveed A. Malik",
    instructorDegree: "ScD Electrical Engineering, Massachusetts Institute of Technology, USA",
    instructorPhotoUrl: null,
    lectureCount: 16,
    semester: CURRENT_SEMESTER,
    announcementCount: 5,
    assignmentCount: 1,
    gdbCount: 0,
    quizCount: 14,
  },
  {
    id: "c-cs304",
    code: "CS304",
    title: "Object Oriented Programming",
    department: "Computer Science/Information Technology",
    creditHours: 3,
    instructorName: "Mr. Muhammad Salman",
    instructorDegree: "MS — Virtual University",
    instructorPhotoUrl: null,
    lectureCount: 45,
    semester: CURRENT_SEMESTER,
    announcementCount: 1,
    assignmentCount: 2,
    gdbCount: 1,
    quizCount: 5,
  },
  {
    id: "c-cs304p",

    code: "CS304P",
    title: "Object Oriented Programming (Practical)",
    department: "Computer Science/Information Technology",
    creditHours: 1,
    instructorName: "Mr. Muhammad Salman",
    instructorDegree: "MS — Virtual University",
    instructorPhotoUrl: null,
    lectureCount: 15,
    semester: CURRENT_SEMESTER,
    announcementCount: 1,
    assignmentCount: 1,
    gdbCount: 0,
    quizCount: 10,
  },
  {
    id: "c-cs604",
    code: "CS604",
    title: "Operating Systems",
    department: "Computer Science/Information Technology",
    creditHours: 3,
    instructorName: "Dr. Adeel Akram",
    instructorDegree: "Ph.D. — NUST",
    instructorPhotoUrl: null,
    lectureCount: 46,
    semester: CURRENT_SEMESTER,
    announcementCount: 1,
    assignmentCount: 2,
    gdbCount: 1,
    quizCount: 4,
  },
  {
    id: "c-cs610",
    code: "CS610",
    title: "Computer Networks",
    department: "Computer Science/Information Technology",
    creditHours: 3,
    instructorName: "Mr. Hammad Khalid Khan",
    instructorDegree:
      "MS Electrical Engineering (Telecommunication) Oklahoma State University USA",
    instructorPhotoUrl: null,
    lectureCount: 46,
    semester: CURRENT_SEMESTER,
    announcementCount: 1,
    assignmentCount: 2,
    gdbCount: 1,
    quizCount: 3,
  },
  {
    id: "c-eng201",
    code: "ENG201",
    title: "Business and Technical English Writing",
    department: "English",
    creditHours: 3,
    instructorName: "Ms. Farah Naz",
    instructorDegree: "MA English — PU",
    instructorPhotoUrl: null,
    lectureCount: 30,
    semester: CURRENT_SEMESTER,
    announcementCount: 1,
    assignmentCount: 1,
    gdbCount: 1,
    quizCount: 3,
  },
  {
    id: "c-isl202",
    code: "ISL202",
    title: "Islamic Studies",
    department: "Islamic Studies",
    creditHours: 2,
    instructorName: "Dr. Imran Ali",
    instructorDegree: "Ph.D. — IIUI",
    instructorPhotoUrl: null,
    lectureCount: 24,
    semester: CURRENT_SEMESTER,
    announcementCount: 0,
    assignmentCount: 1,
    gdbCount: 0,
    quizCount: 5,
  },
  {
    id: "c-pak301",
    code: "PAK301",
    title: "Pakistan Studies",
    department: "Pakistan Studies",
    creditHours: 2,
    instructorName: "Dr. Sana Ahmed",
    instructorDegree: "Ph.D. — QAU",
    instructorPhotoUrl: null,
    lectureCount: 24,
    semester: CURRENT_SEMESTER,
    announcementCount: 0,
    assignmentCount: 1,
    gdbCount: 0,
    quizCount: 3,
  },
];

export const assignments: Assignment[] = [
  {
    id: "a-cs610-1",
    courseId: "c-cs610",
    courseCode: "CS610",
    title: "Assignment No. 1",
    openAt: "2026-04-15T00:00:00.000Z",
    closeAt: "2026-05-01T23:59:00.000Z",
    status: "graded",
    marks: 10,
    totalMarks: 10,
    instructions: "Complete Assignment No. 1 and upload your solution file.",
    assignmentFileUrl: "#assignment-file",
    solutionFileUrl: "#solution-file",
    submittedFileSize: "200.00 KB",
    submittedAt: "2026-04-30T14:23:00.000Z",
    comments: "Good work. Keep it up.",
    gradedFileUrl: "#graded-file",
  },
  {
    id: "a-cs610-2",
    courseId: "c-cs610",
    courseCode: "CS610",
    title: "Assignment No. 2 - Cisco Introduction to Networks Course",
    openAt: "2026-06-15T00:00:00.000Z",
    closeAt: "2026-07-01T23:59:00.000Z",
    status: "expired",
    marks: null,
    totalMarks: 20,
    instructions: "Complete the Cisco Introduction to Networks course assignment.",
    assignmentFileUrl: "#assignment-file",
    solutionFileUrl: null,
    submittedFileSize: null,
    submittedAt: null,
    comments: null,
    gradedFileUrl: null,
  },
  {
    id: "a-cs304-2",
    courseId: "c-cs304",
    courseCode: "CS304",
    title: "Assignment # 2",
    openAt: "2026-07-12T00:00:00.000Z",
    closeAt: "2026-07-26T23:59:00.000Z",
    status: "not_submitted",
    marks: null,
    totalMarks: 20,
    instructions: "Implement OOP concepts as described in the handout.",
    assignmentFileUrl: "#assignment-file",
  },
  {
    id: "a-cs201p-2",
    courseId: "c-cs201p",
    courseCode: "CS201P",
    title: "Assignment No.2",
    openAt: "2026-06-20T00:00:00.000Z",
    closeAt: "2026-07-28T23:59:00.000Z",
    status: "submitted",
    marks: null,
    totalMarks: 15,
    instructions: "Submit your lab source files as a ZIP archive.",
    assignmentFileUrl: "#assignment-file",
    submittedFileSize: "150.00 KB",
    submittedAt: "2026-07-10T10:00:00.000Z",
  },
  {
    id: "a-cs604-1",
    courseId: "c-cs604",
    courseCode: "CS604",
    title: "Assignment # 1",
    openAt: "2026-06-01T00:00:00.000Z",
    closeAt: "2026-06-15T23:59:00.000Z",
    status: "graded",
    marks: 16,
    totalMarks: 20,
    instructions: "Process scheduling worksheet.",
    assignmentFileUrl: "#assignment-file",
    submittedAt: "2026-06-14T09:00:00.000Z",
    comments: "Well structured answers.",
  },
];

export const quizzes: Quiz[] = [
  {
    id: "q-cs304p-10",
    courseId: "c-cs304p",
    courseCode: "CS304P",
    title: "Lab Quiz 10",
    openAt: "2026-07-20T00:00:00.000Z",
    closeAt: "2026-07-22T23:59:00.000Z",
    status: "open",
    durationMinutes: 15,
    totalMarks: 10,
    obtainedMarks: null,
    questions: [
      {
        id: "qq1",
        text: "Which keyword is used to inherit a class in C++?",
        options: ["extends", "implements", ":", "inherits"],
        correctIndex: 2,
      },
      {
        id: "qq2",
        text: "What is encapsulation?",
        options: [
          "Hiding implementation details",
          "Multiple inheritance only",
          "A loop construct",
          "Memory leak",
        ],
        correctIndex: 0,
      },
      {
        id: "qq3",
        text: "A pure virtual function is declared with:",
        options: ["= 0", "virtual pure", "abstract", "override"],
        correctIndex: 0,
      },
    ],
  },
  {
    id: "q-pak301-3",
    courseId: "c-pak301",
    courseCode: "PAK301",
    title: "Quiz No. 3",
    openAt: "2026-07-18T00:00:00.000Z",
    closeAt: "2026-07-25T23:59:00.000Z",
    status: "open",
    durationMinutes: 20,
    totalMarks: 10,
    obtainedMarks: null,
    questions: [
      {
        id: "qq4",
        text: "When was Pakistan created?",
        options: ["1945", "1947", "1956", "1971"],
        correctIndex: 1,
      },
    ],
  },
  {
    id: "q-cs201p-att1",
    courseId: "c-cs201p",
    courseCode: "CS201P",
    title: "Attendance Quiz No. 1",
    openAt: "2026-04-27T00:00:00.000Z",
    closeAt: "2026-04-29T23:59:00.000Z",
    status: "submitted",
    durationMinutes: 5,
    totalMarks: 10,
    obtainedMarks: 10,
    openCloseLabel: "Closed",
    submittedAt: "2026-04-28T20:47:00.000Z",
  },
  {
    id: "q-cs201p-gq1",
    courseId: "c-cs201p",
    courseCode: "CS201P",
    title: "Graded Quiz No.1",
    openAt: "2026-05-05T00:00:00.000Z",
    closeAt: "2026-05-07T23:59:00.000Z",
    status: "submitted",
    durationMinutes: 20,
    totalMarks: 10,
    obtainedMarks: 8,
    openCloseLabel: "Closed",
    submittedAt: "2026-05-06T18:10:00.000Z",
  },
  {
    id: "q-cs201p-att8",
    courseId: "c-cs201p",
    courseCode: "CS201P",
    title: "Attendance Quiz No. 8",
    openAt: "2026-07-15T00:00:00.000Z",
    closeAt: "2026-07-16T23:59:00.000Z",
    status: "submitted",
    durationMinutes: 5,
    totalMarks: 10,
    obtainedMarks: 10,
    openCloseLabel: "Closed",
    submittedAt: "2026-07-15T21:00:00.000Z",
  },
  {
    id: "q-cs201p-gq4",
    courseId: "c-cs201p",
    courseCode: "CS201P",
    title: "Graded Quiz No. 4",
    openAt: "2026-07-01T00:00:00.000Z",
    closeAt: "2026-07-05T23:59:00.000Z",
    status: "result_declared",
    durationMinutes: 20,
    totalMarks: 10,
    obtainedMarks: 9,
    openCloseLabel: "Closed",
    submittedAt: "2026-07-02T19:30:00.000Z",
  },
  {
    id: "q-cs604-3",
    courseId: "c-cs604",
    courseCode: "CS604",
    title: "Semester Quiz # 03",
    openAt: "2026-07-21T00:00:00.000Z",
    closeAt: "2026-07-23T23:59:00.000Z",
    status: "open",
    durationMinutes: 25,
    totalMarks: 15,
    obtainedMarks: null,
    questions: [
      {
        id: "qq5",
        text: "Which scheduling algorithm can cause starvation?",
        options: ["FCFS", "Round Robin", "Priority", "None"],
        correctIndex: 2,
      },
    ],
  },
];

export const gdbs: Gdb[] = [
  {
    id: "g-cs304-1",
    courseId: "c-cs304",
    courseCode: "CS304",
    courseTitle: "Object Oriented Programming",
    title: "Graded Discussion Board",
    openAt: "2026-05-13T00:00:00.000Z",
    closeAt: "2026-05-14T23:59:00.000Z",
    gdbStatus: "Closed",
    submitStatus: "Not Submitted",
    totalMarks: 5,
    obtainedMarks: null,
    questionDescription:
      "Suppose you are developing an online exam system for a university. Different modules of the system need to interact with student data (such as student ID, marks, and results). Some developers suggest using Encapsulation, while others recommend Information Hiding to protect sensitive data.\n\nIn your opinion, which approach (Encapsulation or Information Hiding) is more suitable for this scenario? Justify your answer with solid reasoning. Do not provide any code.",
    instructions: [
      "Do not copy from internet or other students (plagiarism will be marked zero).",
      "Your answer should be clear, relevant, and well reasoned.",
      "Do not paste C++ code in your GDB answer.",
      "Irrelevant or one-line answers may get low marks.",
    ],
    myPost: null,
    prompt:
      "Which approach (Encapsulation or Information Hiding) is more suitable for an online exam system?",
    status: "closed",
    totalPosts: 5590,
    posts: [
      {
        id: "gp1",
        studentId: "BC250210030",
        body: "Encapsulation is more suitable because it bundles data with methods and controls access through well-defined interfaces, which fits an exam system where marks and results must be updated safely.",
        postedAt: "2026-05-19T11:13:00.000Z",
        feedback: "Very Good",
        isMine: false,
      },
      {
        id: "gp2",
        studentId: "BC240401122",
        body: "Information Hiding is better because sensitive student marks should not be directly visible to every module; only authorized operations should expose needed data.",
        postedAt: "2026-05-18T16:40:00.000Z",
        feedback: "Good",
        isMine: false,
      },
      {
        id: "gp3",
        studentId: "BC230201247",
        body: "",
        postedAt: "2026-05-14T10:00:00.000Z",
        feedback: null,
        isMine: true,
      },
      {
        id: "gp4",
        studentId: "BC250115088",
        body: "Both concepts are related, but Encapsulation provides the practical mechanism while Information Hiding is the design principle. For this system Encapsulation with private fields is the right implementation choice.",
        postedAt: "2026-05-17T09:22:00.000Z",
        feedback: "Satisfactory",
        isMine: false,
      },
      {
        id: "gp5",
        studentId: "BC240902011",
        body: "I think just hide everything.",
        postedAt: "2026-05-16T14:05:00.000Z",
        feedback: "Poor",
        isMine: false,
      },
    ],
  },
  {
    id: "g-cs610-1",
    courseId: "c-cs610",
    courseCode: "CS610",
    courseTitle: "Computer Networks",
    title: "Graded Discussion Board",
    openAt: "2026-07-15T00:00:00.000Z",
    closeAt: "2026-07-25T23:59:00.000Z",
    gdbStatus: "Open",
    submitStatus: "Not Submitted",
    totalMarks: 5,
    obtainedMarks: null,
    questionDescription:
      "Discuss advantages of TCP over UDP in reliable applications. Justify with examples from real networks.",
    instructions: [
      "Do not copy content from the internet.",
      "Keep your discussion concise and technical.",
    ],
    myPost: null,
    prompt: "Discuss advantages of TCP over UDP in reliable applications.",
    status: "open",
    totalPosts: 42,
    posts: [
      {
        id: "gp610-1",
        studentId: "BC240110055",
        body: "TCP provides reliable delivery with acknowledgements and retransmission, which is essential for file transfers.",
        postedAt: "2026-07-16T12:00:00.000Z",
        feedback: "Good",
        isMine: false,
      },
    ],
  },
  {
    id: "g-eng201-1",
    courseId: "c-eng201",
    courseCode: "ENG201",
    courseTitle: "Business and Technical English Writing",
    title: "Graded Discussion Board",
    openAt: "2026-07-12T00:00:00.000Z",
    closeAt: "2026-07-22T23:59:00.000Z",
    gdbStatus: "Open",
    submitStatus: "Submitted",
    totalMarks: 5,
    obtainedMarks: null,
    questionDescription: "Share an example of effective technical writing and explain why it works.",
    instructions: ["Use your own words.", "Provide a concrete example."],
    myPost: "A good technical report uses clear headings and active voice.",
    prompt: "Share an example of effective technical writing.",
    status: "submitted",
    totalPosts: 18,
    posts: [
      {
        id: "gp-eng-mine",
        studentId: "BC230201247",
        body: "A good technical report uses clear headings and active voice.",
        postedAt: "2026-07-13T10:20:00.000Z",
        feedback: null,
        isMine: true,
      },
      {
        id: "gp-eng-2",
        studentId: "BC240333001",
        body: "User manuals that use numbered steps are easier to follow than long paragraphs.",
        postedAt: "2026-07-14T08:15:00.000Z",
        feedback: "Very Good",
        isMine: false,
      },
    ],
  },
];

export const announcements: Announcement[] = [
  {
    id: "an-1",
    courseId: "c-cs201p",
    courseCode: "CS201P",
    title: "Recorded Labs Sessions available for students",
    body: "Recorded lab sessions are now available in the course content area.",
    createdAt: "2026-07-21T10:00:00.000Z",
    unread: true,
  },
  {
    id: "an-2",
    courseId: "c-cs201p",
    courseCode: "CS201P",
    title: "Final Term Paper Pattern and Syllabus",
    body: "Please review the final term paper pattern and syllabus uploaded for CS201P.",
    createdAt: "2026-07-20T09:00:00.000Z",
    unread: true,
  },
  {
    id: "an-3",
    courseId: "c-cs201p",
    courseCode: "CS201P",
    title: "Notification Regarding Rescheduled Attendance Quizzes - July 7, 2026",
    body: "Attendance quizzes have been rescheduled. Check the quiz calendar.",
    createdAt: "2026-07-03T08:00:00.000Z",
    unread: false,
  },
  {
    id: "an-4",
    courseId: "c-cs201p",
    courseCode: "CS201P",
    title: "Graded Quiz No. 4",
    body: "Graded Quiz No. 4 has been uploaded.",
    createdAt: "2026-07-02T12:00:00.000Z",
    unread: false,
  },
  {
    id: "an-5",
    courseId: "c-cs201p",
    courseCode: "CS201P",
    title: "Assignment No.2 Uploaded",
    body: "Assignment No.2 has been uploaded. Please submit before the due date.",
    createdAt: "2026-06-30T11:00:00.000Z",
    unread: false,
  },
  {
    id: "an-6",
    courseId: "c-cs304",
    courseCode: "CS304",
    title: "Quiz announcement",
    body: "Next graded quiz will cover polymorphism.",
    createdAt: "2026-07-19T12:00:00.000Z",
    unread: true,
  },
];

export const lessons: Lesson[] = Array.from({ length: 16 }, (_, i) => ({
  id: `les-cs201p-${i}`,
  courseId: "c-cs201p",
  number: i + 1,
  title: i === 0 ? "Lab 0: Intro to course" : `Lab-${i}`,
  duration: i === 0 ? "00:02:40" : i === 15 ? "00:45:10" : `0${(i % 4) + 1}:${String(10 + i).padStart(2, "0")}:00`,
  forumStatus: i === 15 ? "Open" : "Closed",
  forumCount: i === 15 ? 115 : 100 + i * 37,
  hasVideo: true,
  hasPdf: true,
}));

export const activitySessions: ActivitySession[] = [];

export const todos: TodoItem[] = [
  {
    id: "t1",
    type: "assignment",
    title: "CS610: Assignment # 2",
    courseCode: "CS610",
    startAt: "2026-07-10T00:00:00.000Z",
    endAt: "2026-07-24T23:59:00.000Z",
    refId: "a-cs610-2",
    courseId: "c-cs610",
  },
  {
    id: "t2",
    type: "assignment",
    title: "CS304: Assignment # 2",
    courseCode: "CS304",
    startAt: "2026-07-12T00:00:00.000Z",
    endAt: "2026-07-26T23:59:00.000Z",
    refId: "a-cs304-2",
    courseId: "c-cs304",
  },
  {
    id: "t3",
    type: "quiz",
    title: "CS304P: Lab Quiz 10",
    courseCode: "CS304P",
    startAt: "2026-07-20T00:00:00.000Z",
    endAt: "2026-07-22T23:59:00.000Z",
    refId: "q-cs304p-10",
    courseId: "c-cs304p",
  },
  {
    id: "t4",
    type: "quiz",
    title: "PAK301: Quiz No. 3",
    courseCode: "PAK301",
    startAt: "2026-07-18T00:00:00.000Z",
    endAt: "2026-07-25T23:59:00.000Z",
    refId: "q-pak301-3",
    courseId: "c-pak301",
  },
  {
    id: "t5",
    type: "gdb",
    title: "CS610: Graded Discussion",
    courseCode: "CS610",
    startAt: "2026-07-15T00:00:00.000Z",
    endAt: "2026-07-25T23:59:00.000Z",
    refId: "g-cs610-1",
    courseId: "c-cs610",
  },
  {
    id: "t6",
    type: "gdb",
    title: "ENG201: Graded discussion Board",
    courseCode: "ENG201",
    startAt: "2026-07-12T00:00:00.000Z",
    endAt: "2026-07-22T23:59:00.000Z",
    refId: "g-eng201-1",
    courseId: "c-eng201",
  },
  {
    id: "t7",
    type: "quiz_results",
    title: "CS201P: Graded Quiz No. 4 (Results)",
    courseCode: "CS201P",
    startAt: "2026-07-08T00:00:00.000Z",
    endAt: "2026-07-12T23:59:00.000Z",
    refId: "q-cs201p-gq4",
    courseId: "c-cs201p",
  },
  {
    id: "t8",
    type: "datesheet",
    title: "Final Term Datesheet (Spring 2026)",
    courseCode: null,
    startAt: "2026-07-01T00:00:00.000Z",
    endAt: "2026-07-31T23:59:00.000Z",
    refId: null,
    courseId: null,
  },
  {
    id: "t9",
    type: "pending_fee",
    title: "Pending Fee Installment",
    courseCode: null,
    startAt: "2026-07-20T00:00:00.000Z",
    endAt: "2026-07-30T23:59:00.000Z",
    refId: "ch-unpaid",
    courseId: null,
  },
];

export const midtermResults: MidtermRow[] = [
  {
    courseCode: "PAK301",
    courseTitle: "Pakistan Studies",
    marks: 20,
    totalMarks: 40,
    percentage: 50,
    classAverage: 21.71,
    examAttendance: 80.61,
    remarks: null,
  },
  {
    courseCode: "ISL202",
    courseTitle: "Islamic Studies",
    marks: 16,
    totalMarks: 40,
    percentage: 40,
    classAverage: 27.17,
    examAttendance: 81.57,
    remarks: null,
  },
  {
    courseCode: "ENG201",
    courseTitle: "Business and Technical English Writing",
    marks: 16.5,
    totalMarks: 30,
    percentage: 55,
    classAverage: 23.43,
    examAttendance: 90.55,
    remarks: null,
  },
  {
    courseCode: "CS610",
    courseTitle: "Computer Networks",
    marks: 14.5,
    totalMarks: 30,
    percentage: 48,
    classAverage: 19.89,
    examAttendance: 94.43,
    remarks: null,
  },
  {
    courseCode: "CS604",
    courseTitle: "Operating Systems",
    marks: 17.02,
    totalMarks: 30,
    percentage: 57,
    classAverage: 20.06,
    examAttendance: 95.05,
    remarks: null,
  },
  {
    courseCode: "CS304",
    courseTitle: "Object Oriented Programming",
    marks: 20.72,
    totalMarks: 30,
    percentage: 69,
    classAverage: 17.3,
    examAttendance: 92.54,
    remarks: null,
  },
];

export const gradeBook: GradeBookEntry[] = midtermResults.map((m) => ({
  courseCode: m.courseCode,
  courseTitle: m.courseTitle,
  assignments: 15,
  gdbs: m.courseCode.startsWith("CS") || m.courseCode === "ENG201" ? 8 : null,
  quizzes: 12,
  midterm: m.marks,
  finalTerm: null,
  total: null,
  grade: null,
}));

export const gradingScheme: GradingSchemeRow[] = [
  { component: "Assignments", weight: 10 },
  { component: "GDB", weight: 5 },
  { component: "Quizzes", weight: 10 },
  { component: "Midterm", weight: 25 },
  { component: "Final Term", weight: 50 },
];

export const challans: Challan[] = [
  {
    id: "ch-1",
    challanNo: "1002001",
    challanType: "New Admission - Processing",
    payable: 500,
    paid: 500,
    balance: 0,
    dueDate: "2023-03-01",
    paidDate: "2023-02-28",
    paymentMode: "HBL Online",
    status: "paid",
  },
  {
    id: "ch-2",
    challanNo: "1002002",
    challanType: "Security Fee",
    payable: 2000,
    paid: 2000,
    balance: 0,
    dueDate: "2023-03-01",
    paidDate: "2023-03-01",
    paymentMode: "TMB/LB/Online",
    status: "paid",
  },
  {
    id: "ch-3",
    challanNo: "1002455",
    challanType: "Semester/Sports/Fund",
    payable: 1850,
    paid: 1850,
    balance: 0,
    dueDate: "2026-02-15",
    paidDate: "2026-02-10",
    paymentMode: "HBL Online",
    status: "paid",
  },
  {
    id: "ch-unpaid",
    challanNo: "1002890",
    challanType: "Installments_P2",
    payable: 3084,
    paid: 0,
    balance: 3084,
    dueDate: "2026-07-30",
    paidDate: null,
    paymentMode: null,
    status: "unpaid",
  },
];

export const progress: CourseProgress[] = [
  {
    courseId: "c-cs201p",
    courseCode: "CS201P",
    courseTitle: "Introduction to Programming (Practical)",
    assignments: { submitted: 1, notSubmitted: 1 },
    gdb: null,
    quizzes: { submitted: 7, notSubmitted: 1 },
  },
  {
    courseId: "c-cs304",
    courseCode: "CS304",
    courseTitle: "Object Oriented Programming",
    assignments: { submitted: 1, notSubmitted: 1 },
    gdb: { submitted: 0, notSubmitted: 1 },
    quizzes: { submitted: 4, notSubmitted: 1 },
  },
  {
    courseId: "c-cs604",
    courseCode: "CS604",
    courseTitle: "Operating Systems",
    assignments: { submitted: 1, notSubmitted: 1 },
    gdb: { submitted: 0, notSubmitted: 1 },
    quizzes: { submitted: 3, notSubmitted: 1 },
  },
];

export const lectures: LectureSlot[] = [];

export const mails: MailMessage[] = [
  {
    id: "m1",
    from: "CS304 Instructor",
    subject: "Assignment feedback",
    body: "Please review comments on Assignment #1 in LMS.",
    createdAt: "2026-07-18T08:00:00.000Z",
    unread: true,
  },
  {
    id: "m2",
    from: "VU Accounts",
    subject: "Fee reminder",
    body: "Your installment challan is due on 30 July 2026.",
    createdAt: "2026-07-19T11:30:00.000Z",
    unread: true,
  },
  {
    id: "m3",
    from: "Registrar Office",
    subject: "Profile update",
    body: "Kindly keep your profile picture updated for e-ID card.",
    createdAt: "2026-07-10T09:00:00.000Z",
    unread: false,
  },
];

export const notes: Note[] = [
  {
    id: "n1",
    title: "OS scheduling notes",
    body: "FCFS, SJF, Round Robin — revise for midterm.",
    createdAt: "2026-07-22T00:00:00.000Z",
    updatedAt: "2026-07-22T00:00:00.000Z",
  },
];

export const studyScheme: StudySchemeCourse[] = [
  {
    code: "CS101",
    title: "Introduction to Computing",
    type: "Required",
    courseType: "Regular",
    creditHours: 3,
    group: null,
    status: "Studied",
    semester: 1,
  },
  {
    code: "ENG101",
    title: "English Comprehension",
    type: "Required",
    courseType: "Regular",
    creditHours: 3,
    group: null,
    status: "Studied",
    semester: 1,
  },
  {
    code: "CS201",
    title: "Introduction to Programming",
    type: "Required",
    courseType: "Regular",
    creditHours: 3,
    group: null,
    status: "Studied",
    semester: 2,
  },
  {
    code: "CS304",
    title: "Object Oriented Programming",
    type: "Required",
    courseType: "Regular",
    creditHours: 3,
    group: null,
    status: "Studied",
    semester: 7,
  },
  {
    code: "CS605",
    title: "Mobile Application Development",
    type: "Required",
    courseType: "Regular",
    creditHours: 3,
    group: null,
    status: "Pending",
    semester: 8,
  },
  {
    code: "CS615",
    title: "Software Project Management",
    type: "Required",
    courseType: "Regular",
    creditHours: 3,
    group: null,
    status: "Pending",
    semester: 8,
  },
  {
    code: "CS619",
    title: "Final Project",
    type: "Required",
    courseType: "Project",
    creditHours: 6,
    group: null,
    status: "Pending",
    semester: 8,
  },
];

export const studentServices: StudentServiceLink[] = [
  {
    id: "ss1",
    category: "Academics",
    title: "Student Hand Book",
    external: true,
    highlight: false,
  },
  {
    id: "ss2",
    category: "Accounts",
    title: "Need Based Scholarship",
    external: false,
    highlight: false,
  },
  {
    id: "ss3",
    category: "Accounts",
    title: "Security Refund",
    external: false,
    highlight: false,
  },
  {
    id: "ss4",
    category: "Examinations",
    title: "Make your Date Sheet",
    external: false,
    highlight: true,
  },
  {
    id: "ss5",
    category: "Examinations",
    title: "Apply for Degree",
    external: false,
    highlight: false,
  },
  {
    id: "ss6",
    category: "Examinations",
    title: "Apply for Rechecking of Papers",
    external: false,
    highlight: false,
  },
  {
    id: "ss7",
    category: "Examinations",
    title: "Apply for Rescheduling of Papers",
    external: false,
    highlight: false,
  },
  {
    id: "ss8",
    category: "Registrar",
    title: "Semester Freeze",
    external: false,
    highlight: false,
  },
  {
    id: "ss9",
    category: "Registrar",
    title: "Profile Picture Change",
    external: false,
    highlight: false,
  },
  {
    id: "ss10",
    category: "Registrar",
    title: "Duplicate Id Card Request",
    external: false,
    highlight: false,
  },
  {
    id: "ss11",
    category: "Registrar",
    title: "Student Profile Change",
    external: false,
    highlight: false,
  },
];

export const courseSelection: CourseSelection = {
  studentId: DEMO_STUDENT_ID,
  name: "ARSLAN JAFER",
  studyProgram: "BS (Information Technology)",
  cgpa: 2.18,
  effectiveCgpa: 2.38,
  creditsEarned: 65,
  creditsExempted: 0,
  currentSemesterNo: 7,
  semesterLabel: "Semester Spring 2026",
  isOpen: false,
  closedMessage: "The Course Selection for Semester Spring 2026 is Closed.",
};

export const evaluationQuestions: EvaluationQuestion[] = [
  {
    id: "eq1",
    section: "Course Content and Organization",
    text: "The course objectives were clear.",
  },
  {
    id: "eq2",
    section: "Course Content and Organization",
    text: "The course workload was manageable.",
  },
  {
    id: "eq3",
    section: "Student Feedback",
    text: "The teacher was responsive to student needs.",
  },
  {
    id: "eq4",
    section: "Teacher's Knowledge and Presentation",
    text: "The teacher had a thorough knowledge of the subject matter.",
  },
  {
    id: "eq5",
    section: "Assessment and Grading",
    text: "The assessment methods were fair and reflected the course objectives.",
  },
  {
    id: "eq6",
    section: "Overall Evaluation",
    text: "Overall, the course was well-taught.",
  },
];

export const quizAttempts = new Map<string, { answers: number[]; score: number }>();
export const noticeBoardCount = 1;
